replicaCount: 2

image:
  repository: api
  tag: 1
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: fastapi.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

volume:
  mountPath: /models
  size: 1Gi

initContainer:
  image: alpine
  command: ["/bin/sh", "-c"]
  args:
    [
      "echo 'Downloading model...' && wget -O /models/model.pt https://path-to-your-model/model.pt",
    ]
